### ISSUE TITLE
should `pbrt` be its own module?

### ISSUE THREAD

**Issue by c-cube** [mransan/ocaml-protoc#173]
in particular it's a bit of a shame that `ppx_deriving_protobuf` has a very similar runtime module and there's no shared efforts. But also: generated code should only depend on `pbrt`, not `ocaml-protoc`.

**Comment by mransan** [comment]
So what you mean is that Pbrt should be its own opam package so that we can limit the dependency of the generated code on that. I agree that it would be ideal. This would be a precondition to share it with `ppx_deriving_protobug` since ppx_deriving_protobuf being a ppx might have a slower release cycle and a much larger set of dependency. ocaml-protoc used to depend on ppx_deriving_protobuf but because of that I copied over the code.
